//{block name="backend/article/model/attribute/fields" append}
    { name: 'swagAttr21', type: 'string' },
    { name: 'swagAttr22', type: 'string' },
    { name: 'swagAttr23', type: 'string' },
    { name: 'swagAttr24', type: 'string' },
    { name: 'swagAttr25', type: 'string' },
    { name: 'swagAttr26', type: 'string' },
    { name: 'swagAttr27', type: 'string' },
    { name: 'swagAttr28', type: 'string' },
    { name: 'swagAttr29', type: 'string' },
    { name: 'swagAttr30', type: 'string' },
    { name: 'swagAttr31', type: 'string' },
    { name: 'swagAttr32', type: 'string' },
    { name: 'swagAttr33', type: 'string' },
    { name: 'swagAttr34', type: 'string' },
    { name: 'swagAttr35', type: 'string' },
    { name: 'swagAttr36', type: 'string' },
    { name: 'swagAttr37', type: 'string' },
    { name: 'swagAttr38', type: 'string' },
    { name: 'swagAttr39', type: 'string' },
    { name: 'swagAttr40', type: 'string' },
//{/block}